name: 'My Shared Steps'

runs:
  using: 'composite'
  steps:
    - name: ğŸ³ Setup Docker
      uses: docker/setup-buildx-action@v2

    - name: ğŸ”‘ Log into registry ${{ env.REGISTRY }}
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: ğŸ‘·â€â™‚ï¸ Build Image
      uses: docker/build-push-action@v6
      with:
        context: ./modules
        file: ./modules/apps/admin/Dockerfile
        load: true
