name: Admin / Build

on:
  push:
    paths:
      - "modules/apps/admin/**"

env:
  REGISTRY: ghcr.io
  ORGANIZATION: akdasa-studios

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¥ Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: ğŸ³ Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: ğŸ”‘ Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ğŸ› ï¸ Build Image
        uses: docker/build-push-action@v6
        with:
          context: ./modules
          file: ./apps/admin/Dockerfile
          load: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/lectorium-admin:staging

      - name: â¬†ï¸ Push `staging` Image
        run: |
          docker push ${{ env.REGISTRY }}/${{ env.ORGANIZATION }}/lectorium-admin:staging
